filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/app/*.json

    parsers:
      - ndjson:
          overwrite_keys: true
          add_error_key: true
          expand_keys: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
